pipeline {
    agent any

    environment {
        IMAGE_NAME = "springboot-app"
        PROJECT_SUBFOLDER = "GM_back-end"
        DATABASE_URL = credentials('DATABASE_URL')
        DATABASE_USER = credentials('DATABASE_USER')
        DATABASE_PASSWORD = credentials('DATABASE_PASSWORD')
        JWT_SECRET = credentials('JWT_SECRET')
        MAIL_SENDING_EMAIL = credentials('MAIL_SENDING_EMAIL')
        MAIL_APP_PASSWORD = credentials('MAIL_APP_PASSWORD')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Get Commit ID') {
            steps {
                script {
                    env.COMMIT_ID = sh(script: "git -C ${PROJECT_SUBFOLDER} rev-parse --short HEAD", returnStdout: true).trim()
                }
            }
        }

        stage('Build & Test') {
            steps {
                dir(PROJECT_SUBFOLDER) {
                    sh 'mvn clean package'
                    sh 'mvn test'  
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build -t ${IMAGE_NAME}:${COMMIT_ID} -t ${IMAGE_NAME}:latest \
                -f ${PROJECT_SUBFOLDER}/Dockerfile ${PROJECT_SUBFOLDER}
                """
            }
        }

        stage('Remove Old Containers') {
            steps {
                sh "docker rm -f ${IMAGE_NAME} || true"
            }
        }

        stage('Run New Container') {
            steps {
                sh """
                docker run -d -p 8081:8080 --name ${IMAGE_NAME} \
                --restart always \
                -e DATABASE_URL=${DATABASE_URL} \
                -e DATABASE_USER=${DATABASE_USER} \
                -e DATABASE_PASSWORD=${DATABASE_PASSWORD} \
                -e JWT_SECRET=${JWT_SECRET} \
                -e MAIL_SENDING_EMAIL=${MAIL_SENDING_EMAIL} \
                -e MAIL_APP_PASSWORD=${MAIL_APP_PASSWORD} \
                ${IMAGE_NAME}:latest
                """
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful! Running version: ${COMMIT_ID}"
        }
        failure {
            echo "❌ failed! Check logs."
        }
    }
}
